# uses a service principal set up in azure portal
# credentials defined in dev at $HOME/.azure/credentials
#

# Create Resource Group and Azure Web App on existing plan
#
- name: Manage Azure App Service from Ansible
  hosts: localhost

  tasks: 
  - name: create resource group
    azure_rm_resourcegroup:
      name: pwe-ansible-test
      location: westeurope 

  - name: Create Web App
    azure_rm_webapp:
      resource_group: pwe-ansible-test
      name: pwe-ansible-test
      plan: 
        name: pwe-ansible-linux
        resource_group: pwe-ansible-test
      app_settings:
        testkey: testvalue
      frameworks:
        - name: "node"
          version: "6.6"
    register: webapp
  
  - name: Debug Message
    debug:
      var: webapp
